#!/bin/bash
set -e
shopt -s nullglob extglob

cd "`git rev-parse --git-path objects`"

BOLD=$(tput bold)
NORMAL=$(tput sgr0)
RED='\033[0;31m'
GREEN='\033[0;32m'
LIGHT_BLUE='\033[1;34m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

PackedObjectsCount=$((0))
for p in pack/pack-*([0-9a-f]).idx ; do
    current_count=$(git show-index < $p | cut -f 2 -d ' ' | wc -l)
    PackedObjectsCount=$((PackedObjectsCount + current_count))
done

function TagColorSelection() {
  local object_type=$1
  local __resultVariable=$2
  local result=${NC}



  eval $__resultVariable="'${result}'"
}

printf "${GREEN}Packed objects... ${PackedObjectsCount}${NC}\n"
printf "${GREEN}===============================================\n${NC}"
# packed objects
for p in pack/pack-*([0-9a-f]).idx ; do
  git show-index < $p | cut -f 2 -d ' ' | {
   while IFS= read -r current_object_hash
   do
    object_type=$(git cat-file -t $current_object_hash)
    type_color=${NC}
    if [ ${object_type} = "commit" ]; then
      type_color=${LIGHT_RED}
    fi
    if [ ${object_type} = "tree" ]; then
      type_color=${YELLOW}
    fi
    if [ ${object_type} = "blob" ]; then
      type_color=${LIGHT_GREEN}
    fi
    if [ ${object_type} = "tag" ]; then
      type_color=${LIGHT_BLUE}
    fi    
    printf "${current_object_hash} ${type_color}${object_type}${NC}\n"
  done
}
done
printf "${GREEN}===============================================\n${NC}"

LooseObjectsCount=$((0))
for o in [0-9a-f][0-9a-f]/*([0-9a-f]) ; do
    LooseObjectsCount=$((LooseObjectsCount + 1))
done

printf "\n${RED}Loose objects... ${LooseObjectsCount}${NC}\n"
printf "${RED}===============================================\n${NC}"
# loose objects
for o in [0-9a-f][0-9a-f]/*([0-9a-f]) ; do
	current_object_hash="${o/\/}"
	object_type=$(git cat-file -t $current_object_hash)
    type_color=${NC}
    if [ ${object_type} = "commit" ]; then
      type_color=${LIGHT_RED}
    fi
    if [ ${object_type} = "tree" ]; then
      type_color=${YELLOW}
    fi
    if [ ${object_type} = "blob" ]; then
      type_color=${LIGHT_GREEN}
    fi
    if [ ${object_type} = "tag" ]; then
      type_color=${LIGHT_BLUE}
    fi  
    printf "${current_object_hash} ${type_color}${object_type}${NC}\n"
done
printf "${RED}===============================================\n${NC}"

